### ISSUE TITLE
Metadata not included in version

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/wt_versioning#11]
During the [6/29/2020 development call](https://wholetale.readthedocs.io/en/latest/development/meetings/2020-06-29.html) I thought we agreed to version the entire tale, including tale metadata.

The dev notes suggest a consensus around how the current tale metadata state could be included in the workspace under a .wholetale directory that would be included in the version simply as file(s). 

Why was metadata versioning not implemented as discussed?

**Comment by hategan** [comment]
This is a very confused issue.

What is the purpose of this? Is it a bug? Is there an expectation that this feature should be in the code? Is this a note as to how the feature should be introduced in the code? A reminder that the feature should be introduced in the code? Nobody knows...

**Comment by craig-willis** [comment]
Call it a "discussion."  

Per the dev calls, I thought we agreed that metadata would be versioned. In that case it would be a bug or missing feature. But maybe I'm wrong, maybe there was no agreement and that's why it wasn't included.

**Comment by hategan** [comment]
> maybe there was no agreement and that's why it wasn't included.

Or maybe there was nobody available to work on it. My WT allocation is minimal at this moment.

**Comment by Xarthisius** [comment]
> Or maybe there was nobody available to work on it. My WT allocation is minimal and has been so for a few months.

That's fine. The fact that an issue popped up doesn't mean you need to drop everything and fix it. It allows to track things missing for the release and also other people see that something needs to be done and can help.

**Comment by hategan** [comment]
> > Or maybe there was nobody available to work on it. My WT allocation is minimal and has been so for a few months.
> 
> That's fine. The fact that an issue popped up doesn't mean you need to drop everything and fix it. It allows to track things missing for the release and also other people see that something needs to be done and can help.

Well, I think we'd still want to answer Craig's question:

> Why was metadata versioning not implemented as discussed?

**Comment by craig-willis** [comment]
Sorry for the confused issue. It was something I expected based on the dev discussions and I didn't know if there was a reason that it was excluded. If we agree that it should be there and the approach described in the dev note still stands, I'll open a separate feature issue.

**Comment by hategan** [comment]
> Sorry for the confused issue. It was something I expected based on the dev discussions and I didn't know if there was a reason that it was excluded. If we agree that it should be there and the approach described in the dev note still stands, I'll open a separate feature issue.

I don't see why the spirit of the previous agreement should have changed. I'm not sure "manifest via FUSE" is what I'd go with, though. I think something like virtual_resources, where the metadata is stored in a file on the Girder side, is better. Complicating the FUSE layer is something we should avoid, IMO.

**Comment by Xarthisius** [comment]
Resolved as part of https://github.com/whole-tale/wt_versioning/pull/15
